[versions]
java = "21"
minecraft = "1.21.1"

fabric-loom = "1.7.3"
fabric-loader = "0.16.5"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
