name: build
on: { push: {}, pull_request: {} }

jobs:
  build:
    runs-on: ubuntu-24.04
    steps: [
      { uses: 'actions/checkout@v4', with: { fetch-depth: 0 } },
      { uses: 'actions/setup-java@v4', with: { distribution: 'temurin', java-version: 21 } },
      { uses: 'gradle/actions/setup-gradle@v4', with: { gradle-version: 'current' } },
      { run: gradle --no-daemon build },
      { uses: 'actions/upload-artifact@v4', with: { name: 'artifacts.zip', path: 'build/libs/', if-no-files-found: 'error' } }
    ]